### ISSUE TITLE
Figure out what batch data we want in the XML

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/pdf-to-chronam#26]
pdf-to-batch.sh is giving the various python scripts a batch path based on the "raw" batch name, such as `20151201_100000`, rather than the fully prefixed batch name, such as `batch_oru_20151201_100000`.  I *think* think is wrong, but I'm not certain.  I'm not sure if the XML needs that information to be accurate, or if that information is even important when creating a batch.

I think it would be safe to just change the locally-copied directory to include the prefix, but I don't want to mess with that unless it's necessary.

**Comment by lsat12357** [comment]
the batch xml that we've been getting from iarchives has the full batch name.
