### ISSUE TITLE
Should we log low-ascii?

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/pdf-to-chronam#3]
We have no idea right now how many titles/issues/pages have low-ascii issues.  The fixes in PR #2 basically just silence the problems, but don't tell us if we have a widespread issue or if it's primarily one publisher or even just one subset of issues.

With some work we could log low-ascii problems, but it won't be a quick five-minute fix because two systems have independently been stripping low ascii (I use `tidy` first, as it preserves a lot of problem XML by converting to entities, then strip any leftover issues before writing out the final fake-Alto XML).

**Comment by jechols** [comment]
To clarify, "low-ascii issues" are situations I've run across where a PDF's raw text will have certain control characters, such as "^G" (ascii character 7).  These characters aren't valid in XML, so tidy fixes some, and `derivatives/extractxml.py` removes any tidy didn't fix.

One other concern is that the control characters aren't the only issue.  When the text is garbled, it's often complete gibberish even with control characters stripped.  I'm not sure we can do anything about that, but the two seem to be stemming from the same issue.

**Comment by duncanbarth** [comment]
Are we sure that this is just bad OCR, and not a bug in the pdf splitting process? I can't imagine an OCR process thats so broken that *unprintable control characters* are the result of the recognition algorithm.

Well, I guess I can imagine it, but I sort of hope that wouldn't be the case...

**Comment by jechols** [comment]
Born-digital, not OCR.  I don't know where the source of the problem is, but it's definitely not the page splitting.  I looked at the source PDF of an issue directly in Acrobat.  Everything *looks* good.  And most pages are, in fact.  But one page in particular has selectable text that, once copied and pasted, results in utter garbage.  No idea how that could happen.

**Comment by jechols** [comment]
Closing - we decided long ago we can't really fix these problems, and we need to automate the 95% that work even if that means have 5% that are weird or broken.
